import 'package:intl/intl.dart';

import '../models/certificate_config.dart';

class CertificatePackageBuilder {
  CertificatePackageBuilder._();

  static CertificatePackagePlan buildPlan({
    required CertificateGenerationRequest request,
    required ParsedCertificateAddresses addresses,
    required DateTime now,
    bool redactSecrets = false,
  }) {
    final files = fileNamesFor(request);
    final password = redactSecrets ? '<PASSWORD>' : request.password;
    final env = _buildEnv(request, files, password);
    final hosts = _buildHostsExample(request, addresses);
    final readme = _buildReadme(request, addresses, files, env, hosts, now);
    final date = DateFormat('yyyyMMdd').format(now);
    final usageName = usageSlug(request.usage);
    final formatName = formatSlug(request.format);

    return CertificatePackagePlan(
      fileNames: [
        ...files.values,
        'thingsboard.env',
        'hosts.example.txt',
        'README.md',
      ],
      envText: env,
      readmeText: readme,
      hostsText: hosts,
      zipFileName: 'thingsboard-$usageName-$formatName-$date.zip',
    );
  }

  static Map<String, String> fileNamesFor(
      CertificateGenerationRequest request) {
    const ca = 'cafile.pem';
    if (request.format == CertificateOutputFormat.pem) {
      final cert = request.usage == CertificateUsage.mqtts
          ? 'mqttserver.pem'
          : 'server.pem';
      final key = request.usage == CertificateUsage.mqtts
          ? 'mqttserver_key.pem'
          : 'server_key.pem';
      return {
        'certificate': cert,
        'privateKey': key,
        'ca': ca,
      };
    }

    final store = switch (request.usage) {
      CertificateUsage.https => 'keystore.p12',
      CertificateUsage.mqtts => 'mqttserver.p12',
      CertificateUsage.shared => 'thingsboard_ssl.p12',
    };

    return {
      'keystore': store,
      'ca': ca,
    };
  }

  static String usageSlug(CertificateUsage usage) {
    return switch (usage) {
      CertificateUsage.https => 'https',
      CertificateUsage.mqtts => 'mqtts',
      CertificateUsage.shared => 'https-mqtts',
    };
  }

  static String formatSlug(CertificateOutputFormat format) {
    return switch (format) {
      CertificateOutputFormat.pem => 'pem',
      CertificateOutputFormat.pkcs12 => 'pkcs12',
    };
  }

  static String _buildEnv(
    CertificateGenerationRequest request,
    Map<String, String> files,
    String password,
  ) {
    final lines = <String>[
      '# ThingsBoard SSL certificate package generated by IoT DevKit',
    ];

    if (request.usage == CertificateUsage.https ||
        request.usage == CertificateUsage.shared) {
      lines
        ..add('')
        ..add('# HTTPS / Web UI / REST API')
        ..add('SSL_ENABLED=true');

      if (request.format == CertificateOutputFormat.pem) {
        lines
          ..add('SSL_CREDENTIALS_TYPE=PEM')
          ..add('SSL_PEM_CERT=${files['certificate']}')
          ..add('SSL_PEM_KEY=${files['privateKey']}');
      } else {
        lines
          ..add('SSL_CREDENTIALS_TYPE=KEYSTORE')
          ..add('SSL_KEY_STORE_TYPE=PKCS12')
          ..add('SSL_KEY_STORE=${files['keystore']}')
          ..add('SSL_KEY_STORE_PASSWORD=$password')
          ..add('SSL_KEY_ALIAS=${_keyAlias(request)}')
          ..add('SSL_KEY_PASSWORD=$password');
      }
    }

    if (request.usage == CertificateUsage.mqtts ||
        request.usage == CertificateUsage.shared) {
      lines
        ..add('')
        ..add('# MQTTS / MQTT device transport')
        ..add('MQTT_SSL_ENABLED=true')
        ..add('MQTT_SSL_BIND_PORT=8883')
        ..add('MQTT_SSL_PROTOCOL=TLSv1.2');

      if (request.format == CertificateOutputFormat.pem) {
        lines
          ..add('MQTT_SSL_CREDENTIALS_TYPE=PEM')
          ..add('MQTT_SSL_PEM_CERT=${files['certificate']}')
          ..add('MQTT_SSL_PEM_KEY=${files['privateKey']}');
      } else {
        lines
          ..add('MQTT_SSL_CREDENTIALS_TYPE=KEYSTORE')
          ..add('MQTT_SSL_KEY_STORE_TYPE=PKCS12')
          ..add('MQTT_SSL_KEY_STORE=${files['keystore']}')
          ..add('MQTT_SSL_KEY_STORE_PASSWORD=$password')
          ..add('MQTT_SSL_KEY_ALIAS=${_keyAlias(request)}')
          ..add('MQTT_SSL_KEY_PASSWORD=$password');
      }

      lines
        ..add('')
        ..add('# ThingsBoard connectivity check helper')
        ..add('DEVICE_CONNECTIVITY_MQTTS_ENABLED=true')
        ..add('DEVICE_CONNECTIVITY_MQTTS_CA_ROOT_CERT=${files['ca']}');
    }

    return '${lines.join('\n')}\n';
  }

  static String _buildHostsExample(
    CertificateGenerationRequest request,
    ParsedCertificateAddresses addresses,
  ) {
    final dnsNames = addresses.dnsNames.map((address) => address.value).toList()
      ..removeWhere((value) => value == 'localhost');
    final bindingIp = request.hostsBindingIp.trim().isNotEmpty
        ? request.hostsBindingIp.trim()
        : addresses.ips
            .map((address) => address.value)
            .firstWhere((value) => value != '::1', orElse: () => '127.0.0.1');

    final lines = <String>[
      '# macOS / Linux: /etc/hosts',
      r'# Windows: C:\Windows\System32\drivers\etc\hosts',
      '# Add this line only when local DNS does not resolve the domain names.',
      '',
    ];

    if (dnsNames.isEmpty) {
      lines.add('# No custom domain names were provided.');
    } else {
      lines.add('$bindingIp ${dnsNames.join(' ')}');
    }

    return '${lines.join('\n')}\n';
  }

  static String _buildReadme(
    CertificateGenerationRequest request,
    ParsedCertificateAddresses addresses,
    Map<String, String> files,
    String env,
    String hosts,
    DateTime now,
  ) {
    final usage = switch (request.usage) {
      CertificateUsage.https => 'HTTPS',
      CertificateUsage.mqtts => 'MQTTS',
      CertificateUsage.shared => 'HTTPS + MQTTS',
    };
    final format = switch (request.format) {
      CertificateOutputFormat.pem => 'PEM',
      CertificateOutputFormat.pkcs12 => 'PKCS12',
    };
    final san = addresses.addresses.map((address) => '- ${address.label}');

    return '''
# ThingsBoard $usage Certificate Package

Generated: ${DateFormat('yyyy-MM-dd HH:mm:ss').format(now)}
Format: $format
Valid Days: ${request.validDays}

## Files

${files.values.map((file) => '- `$file`').join('\n')}
- `thingsboard.env`
- `hosts.example.txt`

## SAN

${san.join('\n')}

## ThingsBoard Environment Variables

```env
$env```

## Local Hosts Example

```text
$hosts```

## Notes

- Copy the certificate files to a path that the ThingsBoard process can read.
- Apply `thingsboard.env` values through your deployment method, such as Docker environment variables, systemd environment files, or Kubernetes secrets.
- For domain access, the domain must be present in SAN and must resolve to the ThingsBoard server IP.
- `cafile.pem` is the root CA certificate. Import or reference it on clients that need to trust this self-signed CA.
- PEM private keys are generated without passphrase encryption so the package can be built inside IoT DevKit without external tools. Use PKCS12 when password-protected key storage is required.
''';
  }

  static String _keyAlias(CertificateGenerationRequest request) {
    return switch (request.usage) {
      CertificateUsage.https => 'tomcat',
      CertificateUsage.mqtts => 'mqttserver',
      CertificateUsage.shared => 'thingsboard',
    };
  }
}
