import 'package:intl/intl.dart';

import '../models/certificate_config.dart';

class CertificatePackageBuilder {
  CertificatePackageBuilder._();

  static CertificatePackagePlan buildPlan({
    required CertificateGenerationRequest request,
    required ParsedCertificateAddresses addresses,
    required DateTime now,
    bool redactSecrets = false,
  }) {
    final files = fileNamesFor(request);
    final password = redactSecrets ? '<PASSWORD>' : request.password;
    final env = _buildEnv(request, files, password);
    final hosts = _buildHostsExample(request, addresses);
    final readme = _buildReadme(request, addresses, files, env, hosts, now);
    final date = DateFormat('yyyyMMdd').format(now);
    final usageName = usageSlug(request.usage);
    final formatName = formatSlug(request.format);

    return CertificatePackagePlan(
      fileNames: [
        ...files.values,
        'thingsboard.env',
        'hosts.example.txt',
        'README.md',
      ],
      envText: env,
      readmeText: readme,
      hostsText: hosts,
      zipFileName: 'thingsboard-$usageName-$formatName-$date.zip',
    );
  }

  static Map<String, String> fileNamesFor(
      CertificateGenerationRequest request) {
    const ca = 'cafile.pem';
    if (request.format == CertificateOutputFormat.pem) {
      final cert = request.usage == CertificateUsage.mqtts
          ? 'mqttserver.pem'
          : 'server.pem';
      final key = request.usage == CertificateUsage.mqtts
          ? 'mqttserver_key.pem'
          : 'server_key.pem';
      return {
        'certificate': cert,
        'privateKey': key,
        'ca': ca,
      };
    }

    final store = switch (request.usage) {
      CertificateUsage.https => 'keystore.p12',
      CertificateUsage.mqtts => 'mqttserver.p12',
      CertificateUsage.shared => 'thingsboard_ssl.p12',
    };

    return {
      'keystore': store,
      'ca': ca,
    };
  }

  static String usageSlug(CertificateUsage usage) {
    return switch (usage) {
      CertificateUsage.https => 'https',
      CertificateUsage.mqtts => 'mqtts',
      CertificateUsage.shared => 'https-mqtts',
    };
  }

  static String formatSlug(CertificateOutputFormat format) {
    return switch (format) {
      CertificateOutputFormat.pem => 'pem',
      CertificateOutputFormat.pkcs12 => 'pkcs12',
    };
  }

  static String _buildEnv(
    CertificateGenerationRequest request,
    Map<String, String> files,
    String password,
  ) {
    final lines = <String>[
      '# ThingsBoard SSL certificate package generated by IoT DevKit',
    ];

    if (request.usage == CertificateUsage.https ||
        request.usage == CertificateUsage.shared) {
      lines
        ..add('')
        ..add('# HTTPS / Web UI / REST API')
        ..add('SSL_ENABLED=true');

      if (request.format == CertificateOutputFormat.pem) {
        lines
          ..add('SSL_CREDENTIALS_TYPE=PEM')
          ..add('SSL_PEM_CERT=${files['certificate']}')
          ..add('SSL_PEM_KEY=${files['privateKey']}')
          ..add('SSL_PEM_KEY_PASSWORD=');
      } else {
        lines
          ..add('SSL_CREDENTIALS_TYPE=KEYSTORE')
          ..add('SSL_KEY_STORE_TYPE=PKCS12')
          ..add('SSL_KEY_STORE=${files['keystore']}')
          ..add('SSL_KEY_STORE_PASSWORD=$password')
          ..add('SSL_KEY_ALIAS=${_keyAlias(request)}')
          ..add('SSL_KEY_PASSWORD=$password');
      }
    }

    if (request.usage == CertificateUsage.mqtts ||
        request.usage == CertificateUsage.shared) {
      lines
        ..add('')
        ..add('# MQTTS / MQTT device transport')
        ..add('MQTT_SSL_ENABLED=true')
        ..add('MQTT_SSL_BIND_PORT=8883')
        ..add('MQTT_SSL_PROTOCOL=TLSv1.2');

      if (request.format == CertificateOutputFormat.pem) {
        lines
          ..add('MQTT_SSL_CREDENTIALS_TYPE=PEM')
          ..add('MQTT_SSL_PEM_CERT=${files['certificate']}')
          ..add('MQTT_SSL_PEM_KEY=${files['privateKey']}')
          ..add('MQTT_SSL_PEM_KEY_PASSWORD=');
      } else {
        lines
          ..add('MQTT_SSL_CREDENTIALS_TYPE=KEYSTORE')
          ..add('MQTT_SSL_KEY_STORE_TYPE=PKCS12')
          ..add('MQTT_SSL_KEY_STORE=${files['keystore']}')
          ..add('MQTT_SSL_KEY_STORE_PASSWORD=$password')
          ..add('MQTT_SSL_KEY_ALIAS=${_keyAlias(request)}')
          ..add('MQTT_SSL_KEY_PASSWORD=$password');
      }

      lines
        ..add('')
        ..add('# ThingsBoard connectivity check helper')
        ..add('DEVICE_CONNECTIVITY_MQTTS_ENABLED=true')
        ..add('DEVICE_CONNECTIVITY_MQTTS_CA_ROOT_CERT=${files['ca']}');
    }

    return '${lines.join('\n')}\n';
  }

  static String _buildHostsExample(
    CertificateGenerationRequest request,
    ParsedCertificateAddresses addresses,
  ) {
    final dnsNames = addresses.dnsNames.map((address) => address.value).toList()
      ..removeWhere((value) => value == 'localhost');
    final bindingIp = request.hostsBindingIp.trim().isNotEmpty
        ? request.hostsBindingIp.trim()
        : addresses.ips
            .map((address) => address.value)
            .firstWhere((value) => value != '::1', orElse: () => '127.0.0.1');

    final lines = <String>[
      '# macOS / Linux: /etc/hosts',
      r'# Windows: C:\Windows\System32\drivers\etc\hosts',
      '# Add this line only when local DNS does not resolve the domain names.',
      '',
    ];

    if (dnsNames.isEmpty) {
      lines.add('# No custom domain names were provided.');
    } else {
      lines.add('$bindingIp ${dnsNames.join(' ')}');
    }

    return '${lines.join('\n')}\n';
  }

  static String _buildReadme(
    CertificateGenerationRequest request,
    ParsedCertificateAddresses addresses,
    Map<String, String> files,
    String env,
    String hosts,
    DateTime now,
  ) {
    final usage = switch (request.usage) {
      CertificateUsage.https => 'HTTPS',
      CertificateUsage.mqtts => 'MQTTS',
      CertificateUsage.shared => 'HTTPS + MQTTS',
    };
    final format = switch (request.format) {
      CertificateOutputFormat.pem => 'PEM',
      CertificateOutputFormat.pkcs12 => 'PKCS12',
    };
    final san = addresses.addresses.map((address) => '- ${address.label}');

    return '''
# ThingsBoard $usage Certificate Package

Generated: ${DateFormat('yyyy-MM-dd HH:mm:ss').format(now)}
Format: $format · Valid Days: ${request.validDays}

> ⚠️ **This is a PRIVATE self-signed root CA.** Browsers / MQTT clients /
> curl will refuse HTTPS until BOTH of the following are true on the
> client side:
> 1. `cafile.pem` is installed as a **trusted root** in the client
>    truststore (OS keychain, browser, Java cacerts, Node, etc.).
> 2. The host you connect to is listed in the SAN below.
>
> 90% of "HTTPS won't open" reports against ThingsBoard with a self-signed
> cert come down to one of these two — see Diagnose section below.

## SAN — the cert is only valid for these hosts

${san.join('\n')}

If your real ThingsBoard host (LAN IP / domain) is **not** in this list,
regenerate the certificate with the correct hosts entered in the
"Certificate SAN Addresses" field. The defaults `localhost / 127.0.0.1 /
::1` only cover local-only access.

## Files

${files.values.map((file) => '- `$file`').join('\n')}
- `thingsboard.env`
- `hosts.example.txt`

## Trust the CA on the client

```bash
# macOS  — add cafile.pem as a trusted system root
sudo security add-trusted-cert -d -r trustRoot \\
  -k /Library/Keychains/System.keychain cafile.pem

# Linux  — Debian/Ubuntu
sudo cp cafile.pem /usr/local/share/ca-certificates/iot-devkit-ca.crt
sudo update-ca-certificates

# Linux  — RHEL/CentOS/Fedora
sudo cp cafile.pem /etc/pki/ca-trust/source/anchors/iot-devkit-ca.crt
sudo update-ca-trust

# Java   — append to JDK cacerts (default truststore pass: changeit)
sudo keytool -import -trustcacerts -noprompt -alias iot-devkit-ca \\
  -file cafile.pem -keystore \$JAVA_HOME/lib/security/cacerts

# Windows — PowerShell (Administrator)
Import-Certificate -FilePath cafile.pem `
  -CertStoreLocation Cert:\\LocalMachine\\Root
```

## Deploy to ThingsBoard (Docker example)

Mount the cert dir into the container and point env vars at the
**container path**, not the host path:

```yaml
services:
  tb:
    image: thingsboard/tb-postgres
    volumes:
      - ./certs:/config/certs:ro
    environment:
      SSL_ENABLED: "true"
      SSL_CREDENTIALS_TYPE: PEM
      SSL_PEM_CERT: /config/certs/${files['certificate']}
      SSL_PEM_KEY:  /config/certs/${files['privateKey']}
```

## Diagnose TLS in 5 seconds

```bash
# Replace <host>:<port> with what you actually access (e.g. tb.local:443)
openssl s_client -connect <host>:<port> -CAfile cafile.pem \\
  -servername <host> </dev/null 2>&1 | tail -25
```

Read the last lines:
- `Verify return code: 0 (ok)`             → cert + chain OK on this client
- `unable to get local issuer certificate` → CA not trusted (do step above)
- `Hostname mismatch` / `not match`        → host not in SAN (regenerate)
- `Connection refused / timeout`           → wrong port / TB SSL disabled

## ThingsBoard Environment Variables

```env
$env```

## Local Hosts Example

```text
$hosts```

## Notes

- PEM private keys are generated **unencrypted** so the package can be
  built inside IoT DevKit without external tools. ThingsBoard's
  `SslUtil.readPrivateKey` accepts unencrypted PEM and ignores
  `SSL_PEM_KEY_PASSWORD` in that case (verified against TB 4.1 source).
  Use PKCS12 format if you need a password-protected keystore.
- Apply `thingsboard.env` values through your deployment method (Docker
  env, systemd EnvironmentFile, Kubernetes secret, ...).
- For domain access, the domain must be present in SAN **and** must
  resolve to the ThingsBoard server IP on the client (DNS / hosts file).
''';
  }

  static String _keyAlias(CertificateGenerationRequest request) {
    return switch (request.usage) {
      CertificateUsage.https => 'tomcat',
      CertificateUsage.mqtts => 'mqttserver',
      CertificateUsage.shared => 'thingsboard',
    };
  }
}
